// webloc.js — 网页端(display/query/register/checkin/race_control/control/leaderboard)中文/English 双语支持
// 跟桌面WPF端 SwimmingScoreboard/Localization.cs 的 Loc 类是同一个思路, 但这是纯浏览器JS实现,
// 不共享任何代码(技术栈不同), 只共享"key -> [中文, English]"这个总表 + 同样的安全网原则:
//   - t(key) 查不到key就退化显示key本身, 不抛异常/不崩页面(参照 Loc.T 的安全网)。
//   - 只翻译"纯UI文案"(按钮/标签/提示/表头等), 不碰任何会 send 给服务器或参与 ===/==
//     比较的协议字段值(比如 gender/stage 的原始中文值、status 的 DNS/DNF/DSQ 代码等)——
//     这些值本身永远保持不变, 只在"给人看"的位置上包一层 t()/genderDisplay()/stageDisplay()
//     做展示层转换, 参照桌面端 Loc.GenderDisplay/Loc.StageDisplay 的模式。
var WebLoc = (function () {
    var table = {
        // ── 通用 ──────────────────────────────────────────────
        "Str_Common_Confirm": ["确定", "OK"],
        "Str_Common_Cancel": ["取消", "Cancel"],
        "Str_Common_Close": ["关闭", "Close"],
        "Str_Common_Print": ["打印", "Print"],
        "Str_Common_Server": ["服务器", "Server"],
        "Str_Common_Connect": ["连接", "Connect"],
        "Str_Common_ScheduleNav": ["赛程导航", "Schedule"],
        "Str_Common_WaitingSchedule": ["等待赛程数据…", "Waiting for schedule data…"],
        "Str_Common_NoSchedule": ["暂无赛程", "No schedule yet"],
        "Str_Common_ConnectServerTitle": ["连接主服务器", "Connect to Server"],
        "Str_Common_ServerIpLabel": ["服务器IP地址", "Server IP Address"],
        "Str_Common_ServerIpPlaceholder": ["如 192.168.1.100", "e.g. 192.168.1.100"],
        "Str_Common_Connecting": ["连接中...", "Connecting..."],
        "Str_Common_Connected": ["已连接", "Connected"],
        "Str_Common_Disconnected": ["未连接", "Not connected"],
        "Str_Common_NotConnectedParen": ["（未连接）", "(Not connected)"],
        "Str_Common_ConnClosed": ["已断开", "Disconnected"],
        "Str_Common_ConnError": ["连接错误", "Connection error"],
        "Str_Common_ConnFailedFmt": ["无法连接: {0}", "Unable to connect: {0}"],
        "Str_Common_SessionNumFmt": ["第{0}场", "Session {0}"],
        "Str_Common_HeatOfFmt": ["第{0}组（共{1}组）", "Heat {0} (of {1})"],
        "Str_Common_HeatNumFmt": ["第{0}组", "Heat {0}"],
        "Str_Common_LegFmt": ["第{0}棒", "Leg {0}"],
        "Str_Common_Leg1": ["第1棒", "Leg 1"],
        "Str_Common_Leg2": ["第2棒", "Leg 2"],
        "Str_Common_Leg3": ["第3棒", "Leg 3"],
        "Str_Common_Leg4": ["第4棒", "Leg 4"],
        "Str_Common_CountParenFmt": ["（共 {0} {1}）", " ({0} {1})"],
        "Str_Common_LangToggle": ["English", "中文"],
        // 组次状态(数字 HEAT_STATUS -> 展示文本; 底层比较用的是数字, 这些只是展示层)
        "Str_HeatStatus_Pending": ["未开始", "Not started"],
        "Str_HeatStatus_CheckedIn": ["已检录", "Checked in"],
        "Str_HeatStatus_Running": ["进行中", "In progress"],
        "Str_HeatStatus_Done": ["已完赛", "Finished"],
        "Str_HeatStatus_Confirmed": ["已确认", "Confirmed"],
        "Str_HeatStatus_Cancelled": ["已取消", "Cancelled"],
        // 性别/赛次 展示层转换(底层值保持中文, 参照 Loc.GenderDisplay/Loc.StageDisplay)
        "Str_Gender_Male": ["男", "Male"],
        "Str_Gender_Female": ["女", "Female"],
        "Str_Gender_Mixed": ["混合", "Mixed"],
        "Str_Stage_Prelim": ["预赛", "Prelim"],
        "Str_Stage_Semi": ["半决赛", "Semifinal"],
        "Str_Stage_Final": ["决赛", "Final"],

        // ── checkin.html ──────────────────────────────────────
        "Str_Checkin_PageTitle": ["游泳竞赛检录台", "Swimming Check-in Station"],
        "Str_Checkin_ConfirmBtn": ["确认检录", "Confirm Check-in"],
        "Str_Checkin_SelectHeatPrompt": ["请从左侧选择比赛组", "Select a heat from the left"],
        "Str_Checkin_SelectHeatFull": ["请从左侧赛程导航中选择一个比赛组", "Select a heat from the schedule navigation on the left"],
        "Str_Checkin_ResultSubmitted": ["检录结果已提交", "Check-in result submitted"],
        "Str_Checkin_ResultRejectedFmt": ["检录未提交：{0}", "Check-in not submitted: {0}"],
        "Str_Checkin_ServerRejectedDefault": ["服务器拒绝了这次提交", "The server rejected this submission"],
        "Str_Checkin_HeatRunningLocked": ["该组正在比赛中", "This heat is currently racing"],
        "Str_Checkin_HeatConfirmedLocked": ["该组成绩已确认", "This heat's results are confirmed"],
        "Str_Checkin_LockedSuffixFmt": ["{0}，不能再检录，仅供查看。", "{0} — check-in is locked, view only."],
        "Str_Checkin_TeamCountUnit": ["队", "team(s)"],
        "Str_Checkin_PersonCountUnit": ["人", "athlete(s)"],
        "Str_Checkin_DefaultCompName": ["游泳竞赛", "Swimming Competition"],
        "Str_Checkin_PrintSuffix": ["检录表", "Check-in Sheet"],
        "Str_Checkin_PrintCountFmt": ["共 {0} {1}", "Total {0} {1}"],
        "Str_Checkin_PrintTimeFmt": ["打印时间: {0}", "Printed: {0}"],
        "Str_Checkin_RefereeSignature": ["检录裁判签字: ________________", "Check-in Referee Signature: ________________"],
        "Str_Checkin_ColLane": ["泳道", "Lane"],
        "Str_Checkin_ColBib": ["号码", "Bib"],
        "Str_Checkin_ColName": ["姓名", "Name"],
        "Str_Checkin_ColNameRelaySuffix": ["（队 / 队员）", " (Team / Member)"],
        "Str_Checkin_ColId": ["身份证号", "ID Number"],
        "Str_Checkin_ColTeam": ["单位", "Team"],
        "Str_Checkin_ColNote": ["备注（检录）", "Note (Check-in)"],
        "Str_Checkin_NoSwimmers": ["该组暂无运动员报名", "No swimmers registered for this heat"],
        "Str_Checkin_StatusNormal": ["正常", "Normal"],
        "Str_Checkin_StatusDNS": ["DNS 弃权/未到", "DNS Absent/No-show"],
        "Str_Checkin_StatusDNF": ["DNF 中途退出", "DNF Did not finish"],
        "Str_Checkin_StatusDSQ": ["DSQ 犯规", "DSQ Disqualified"],
        "Str_Checkin_StatPresent": ["实到", "Present"],
        "Str_Checkin_StatTeamCount": ["队数", "Teams"],
        "Str_Checkin_StatTotalCount": ["总数", "Total"],
        "Str_Checkin_StatMemberPresent": ["队员实到", "Members present"],
        "Str_Checkin_StatAbsent": ["弃权", "Absent"],
        "Str_Checkin_StatDNF": ["中退", "DNF"],
        "Str_Checkin_StatDSQ": ["犯规", "DSQ"],
        "Str_Checkin_StatMemberAbsent": ["缺席队员", "Absent members"],
        "Str_Checkin_Unsaved": ["(未保存)", "(unsaved)"],
        "Str_Checkin_SelectHeatFirst": ["请先选择比赛组", "Please select a heat first"],
        "Str_Checkin_NotConnected": ["未连接主服务器", "Not connected to server"],
        "Str_Checkin_CannotCheckinLocked": ["该组正在比赛中或成绩已确认，不能再检录。", "This heat is racing or confirmed — check-in is locked."],
        "Str_Checkin_ConfirmSubmit": ["确认提交本组检录结果？\n\n将把备注中的 DNS/DNF/DSQ 状态同步到主服务器。", "Submit check-in results for this heat?\n\nThe DNS/DNF/DSQ statuses in the notes will be synced to the server."],
        "Str_Checkin_ConfirmSwitchHeat": ["当前组有未保存的备注修改，切换后将丢失。确定切换？", "This heat has unsaved note changes that will be lost if you switch. Continue?"],

        // ── 更多通用词（register/query/display 共用） ──────────
        "Str_Common_SystemName": ["游泳赛事管理系统", "Swimming Event Management System"],
        "Str_Common_Fullscreen": ["全屏", "Fullscreen"],
        "Str_Common_Query": ["查询", "Search"],
        "Str_Common_Name": ["姓名", "Name"],
        "Str_Common_Gender": ["性别", "Gender"],
        "Str_Common_SelectGender": ["请选择性别", "Select gender"],
        "Str_Common_PleaseSelectGender": ["请选择性别", "Please select a gender"],
        "Str_Common_BirthDate": ["出生日期", "Date of Birth"],
        "Str_Common_Country": ["代表队", "Team"],
        "Str_Common_CountryShort": ["单位简称", "Team Abbr."],
        "Str_Common_AgeGroup": ["组别", "Age Group"],
        "Str_Common_SelectAgeGroup": ["请选择组别", "Select age group"],
        "Str_Common_OptionalParen": ["（可选）", "(optional)"],
        "Str_Common_Event": ["项目", "Event"],
        "Str_Common_EntryTime": ["报名成绩", "Entry Time"],
        "Str_Common_ClearForm": ["清空当前表单", "Clear Form"],
        "Str_Common_Notes": ["备注", "Notes"],
        "Str_Common_IdNumber": ["身份证号", "ID Number"],
        "Str_Common_BibShort": ["参赛号", "Bib"],
        "Str_Common_NotSpecified": ["不指定", "Not specified"],
        "Str_Common_Querying": ["查询中…", "Searching…"],
        "Str_Common_NotConnectedShort": ["未连接服务器", "Not connected to server"],
        "Str_Common_NotConnectedQuery": ["未连接服务器，无法查询", "Not connected to server — cannot search"],
        "Str_Common_FormErrorHeader": ["表单未通过校验，请补全以下字段：", "The form did not pass validation — please complete the following fields:"],
        "Str_Common_Edit": ["修改", "Edit"],
        "Str_Common_Delete": ["删除", "Delete"],
        "Str_Common_Know": ["知道了", "Got it"],
        "Str_Common_BackToEdit": ["返回修改", "Back to Edit"],
        "Str_Common_UnnamedEntryFmt": ["第{0}条", "Entry {0}"],
        "Str_Common_UnknownReasonDefault": ["未知原因", "Unknown reason"],
        "Str_Common_ValidationFailedDefault": ["校验未通过", "Validation failed"],
        "Str_Common_VersionMismatchFmt": ["⚠ 本页版本 {0} 与主服务器 {1} 不一致 —— 请按 Ctrl+F5 强制刷新。仍不一致说明这台机器上的 Web 目录没跟 exe 一起更新。(点此关闭)",
            "⚠ This page's version {0} does not match the server's {1} — press Ctrl+F5 to force-refresh. If it still mismatches, this machine's Web folder wasn't updated together with the exe. (Click to dismiss)"],

        // ── register.html ─────────────────────────────────────
        "Str_Register_PageTitle": ["运动员注册", "Athlete Registration"],
        "Str_Register_ChangeServerBtn": ["🔄 切换服务器IP", "🔄 Change Server IP"],
        "Str_Register_ChangeServerTip": ["点此随时切换到另一台主服务器（无需先断开）", "Click to switch to another server at any time (no need to disconnect first)"],
        "Str_Register_SubmittedDefault": ["报名信息已提交成功！", "Registration submitted successfully!"],
        "Str_Register_EditThisSubmission": ["修改本次报名", "Edit This Registration"],
        "Str_Register_TabPersonal": ["👤 个人项目报名", "👤 Individual Events"],
        "Str_Register_TabRelay": ["👥 接力队报名", "👥 Relay Teams"],
        "Str_Register_RelayCardTitle": ["接力队报名", "Relay Team Registration"],
        "Str_Register_QueryCardTitle": ["查询 / 修改我已经提交的报名", "Look Up / Edit My Registration"],
        "Str_Register_LabelBib": ["参赛号", "Bib Number"],
        "Str_Register_BibPlaceholder": ["如 001", "e.g. 001"],
        "Str_Register_LabelNameCountry": ["或 姓名 + 代表队", "Or Name + Team"],
        "Str_Common_NamePlaceholder": ["姓名", "Name"],
        "Str_Common_CountryPlaceholder": ["代表队", "Team"],
        "Str_Register_PersonalCardTitle": ["个人项目报名", "Individual Event Registration"],
        "Str_Register_RequiredNote": ["（带 * 为必填）", " (* required)"],
        "Str_Register_DateFormatTip": ["格式：yyyy-MM-dd（4 位年份）", "Format: yyyy-MM-dd (4-digit year)"],
        "Str_Register_IdLabel": ["身份证号（可选，国际选手可用护照号等证件号）", "ID Number (optional — international athletes may use a passport or other ID number)"],
        "Str_Register_IdPlaceholder": ["选填，不限位数/格式", "Optional, any format"],
        "Str_Register_Phone": ["联系电话", "Phone"],
        "Str_Register_CsaNumber": ["协会注册号", "Association Reg. No."],
        "Str_Register_AgeGroupTip": ["组别由服务器同步，可在主控软件「比赛参数设置管理→组别」里维护", "Age groups are synced from the server; maintain them in the main app under \"Competition Parameters → Age Groups\""],
        "Str_Register_EventsTitle": ["参赛项目", "Events"],
        "Str_Register_AtLeastOne": ["*（至少 1 项）", "* (at least 1)"],
        "Str_Register_AddEventBtn": ["+ 添加参赛项目", "+ Add Event"],
        "Str_Register_AddToQueueBtn": ["+ 添加到报名列表", "+ Add to Registration List"],
        "Str_Register_PersonalHint": ["录入完一人后点\"添加到报名列表\"，再录入下一人；全部录入完成后在下方\"待提交报名列表\"统一提交。",
            "After entering one athlete, click \"Add to Registration List\", then enter the next; once done, submit all at once from the \"Pending Registrations\" list below."],
        "Str_Register_QueueTitle": ["待提交报名列表", "Pending Registrations"],
        "Str_Register_QueueHint": ["提交后服务器会逐条返回结果。未通过的条目会保留在列表里并显示原因，修改后再次\"全部提交\"。",
            "The server returns a result for each entry after submitting. Entries that fail stay in the list with the reason shown — fix them and \"Submit All\" again."],
        "Str_Register_QueryRelayTitle": ["查询已报名接力队（改棒次用）", "Look Up a Registered Relay Team (to edit legs)"],
        "Str_Register_TeamNamePlaceholder": ["输入队名，如 北京队A", "Enter team name, e.g. Beijing Team A"],
        "Str_Register_QueryAndFillBtn": ["查询并回填", "Look Up & Fill"],
        "Str_Register_TeamNameLabel": ["队名", "Team Name"],
        "Str_Register_LegArrangement": ["棒次安排（4 棒姓名必填，同一队伍报多个接力项目共用这组棒次）", "Leg Assignments (all 4 names required; the same team sharing multiple relay events uses this one set of legs)"],
        "Str_Register_NameRequiredPlaceholder": ["姓名 *", "Name *"],
        "Str_Register_RelayEventsTitle": ["接力项目", "Relay Events"],
        "Str_Register_AddRelayEventBtn": ["+ 添加接力项目", "+ Add Relay Event"],
        "Str_Register_AddRelayQueueBtn": ["+ 添加到接力报名列表", "+ Add to Relay Registration List"],
        "Str_Register_RelayHint": ["录入完一支队（棒次+项目）后点\"添加到接力报名列表\"，再录入下一支队；全部录入完成后统一提交。",
            "After entering one team (legs + events), click \"Add to Relay Registration List\", then enter the next; submit all once done."],
        "Str_Register_RelayQueueTitle": ["待提交接力报名列表", "Pending Relay Registrations"],
        "Str_Register_RelayQueueHint": ["提交后服务器会逐条（队×项目）返回结果。未通过的条目请回到上方表单修改后重新添加。",
            "The server returns a result for each (team × event) entry. For entries that fail, go back to the form above, fix them, and re-add."],
        "Str_Register_ConfirmClose": ["确定要关闭注册终端？", "Close the registration terminal?"],
        "Str_Register_ConnectedFmt": ["已连接服务器 {0}", "Connected to server {0}"],
        "Str_Register_ConnLostRetrying": ["连接断开，重连中...", "Disconnected, reconnecting..."],
        "Str_Register_ConnFailRetry": ["连接失败，是否重新设置服务器地址？", "Connection failed — reset the server address?"],
        "Str_Register_EnterServerIpPrompt": ["请输入服务器IP地址:", "Enter the server IP address:"],
        "Str_Register_DefaultAthlete": ["运动员", "the athlete"],
        "Str_Register_SuccessBannerFmt": ["报名成功！{0}（参赛号 {1}），表单已自动重置可继续注册下一位。", "Registration succeeded! {0} (Bib {1}) — the form has been reset so you can register the next athlete."],
        "Str_Register_SuccessStatusFmt": ["报名成功！参赛号: {0}", "Registration succeeded! Bib: {0}"],
        "Str_Register_FailStatusFmt": ["报名失败: {0}", "Registration failed: {0}"],
        "Str_Register_UnknownError": ["未知错误", "Unknown error"],
        "Str_Register_QueryNeedInput": ["请输入参赛号，或同时输入姓名+代表队", "Enter a bib number, or both name and team"],
        "Str_Register_RelayQueryNeedTeam": ["请输入队名", "Enter a team name"],
        "Str_Register_RelayNotFoundDefault": ["未找到该队", "Team not found"],
        "Str_Register_RelayFilledFmt": ["✔ 已回填: {0} ({1} 棒)，修改后点「+ 添加接力项目」「+ 添加到接力报名列表」「全部提交接力报名」，服务器会按队名+性别+项目+组别覆盖更新",
            "✔ Filled in: {0} ({1} legs). After editing, click \"+ Add Relay Event\" → \"+ Add to Relay Registration List\" → \"Submit All Relay Registrations\" — the server will overwrite by team name + gender + event + age group"],
        "Str_Register_QueryNotFoundDefault": ["未找到对应报名记录", "No matching registration found"],
        "Str_Register_LoadedForEditFmt": ["已加载报名信息（参赛号 {0}），可修改后再次提交。", "Registration loaded (Bib {0}) — edit and submit again."],
        "Str_Register_EditModeStatusFmt": ["修改模式：参赛号 {0}。提交将覆盖旧记录。", "Edit mode: Bib {0}. Submitting will overwrite the previous record."],
        "Str_Register_DuplicateEvent": ["已添加此项目，不能重复！", "This event has already been added!"],
        "Str_Register_NoEventsYet": ["尚未添加参赛项目", "No events added yet"],
        "Str_Register_NoRelayEventsYet": ["尚未添加接力项目", "No relay events added yet"],
        "Str_Register_EntryTimeLabelFmt": ["报名: {0}", "Entry: {0}"],
        "Str_Register_RemoveEventBtn": ["X 删除此项", "X Remove"],
        "Str_Register_PleaseName": ["请填写姓名", "Please enter a name"],
        "Str_Register_PleaseBirthDate": ["请填写出生日期", "Please enter a date of birth"],
        "Str_Register_BirthDateFormatErr": ["出生日期格式应为 yyyy-MM-dd", "Date of birth must be in yyyy-MM-dd format"],
        "Str_Register_PleaseAgeGroup": ["请选择组别", "Please select an age group"],
        "Str_Register_PleaseCountry": ["请填写代表队", "Please enter a team"],
        "Str_Register_PleaseAtLeastOneEvent": ["请至少添加一个参赛项目", "Please add at least one event"],
        "Str_Register_JoinedQueueMsg": ["已加入报名列表，可继续录入下一位", "Added to the registration list — you can enter the next athlete"],
        "Str_Register_EditingQueueFmt": ["正在编辑队列第 {0} 条，修改后请再次点\"添加到报名列表\"", "Editing entry {0} — after making changes, click \"Add to Registration List\" again"],
        "Str_Register_QueueEmptyHint": ["列表为空，请先在上方录入运动员后\"添加到报名列表\"", "The list is empty — enter an athlete above, then \"Add to Registration List\""],
        "Str_Register_SubmitAllPersonFmt": ["全部提交报名（{0} 人）", "Submit All ({0} athletes)"],
        "Str_Register_QueueCountFmt": ["共 {0} 人", "{0} total"],
        "Str_Register_QiMetaEventsFmt": ["{0} 项", "{0} event(s)"],
        "Str_Register_QiMetaBibFmt": [" / 号 {0}", " / Bib {0}"],
        "Str_Register_QueueEmptySubmit": ["列表为空，请先添加", "The list is empty — add an entry first"],
        "Str_Register_SubmittingFmt": ["正在提交 {0} 人报名……等待服务器结果", "Submitting {0} registration(s)… waiting for the server"],
        "Str_Register_ResultOkTitle": ["报名提交成功", "Registration Submitted"],
        "Str_Register_ResultOkSummaryFmt": ["主服务器已通过本次报名，共 {0} 人，相关数据已写入比赛系统。", "The server accepted this registration — {0} athlete(s), and the data has been written to the competition system."],
        "Str_Register_ResultOkBibFmt": ["（参赛号 {0}）", " (Bib {0})"],
        "Str_Register_ResultOkAddedFmt": ["：{0} 项", ": {0} event(s)"],
        "Str_Register_ResultFailTitle": ["报名未通过", "Registration Rejected"],
        "Str_Register_ResultFailDefaultMsg": ["主服务器反馈：部分条目未通过校验。请修改下方红色标记的条目后再次\"全部提交报名\"。",
            "Server feedback: some entries failed validation. Fix the entries marked red below, then \"Submit All\" again."],
        "Str_Register_PassedHeader": ["报名通过：", "Accepted:"],
        "Str_Register_FailedHeader": ["未通过项：", "Rejected:"],
        "Str_Register_FailedHint": ["提示：在下方\"待提交报名列表\"中点对应条目\"修改\"按钮调出表单更正后，再次点\"全部提交报名\"。",
            "Tip: click \"Edit\" on the entry in the \"Pending Registrations\" list below to correct it, then \"Submit All\" again."],
        "Str_Register_PleaseTeamName": ["请填写队名", "Please enter a team name"],
        "Str_Register_PleaseLegNameFmt": ["请填写第{0}棒姓名", "Please enter the name for leg {0}"],
        "Str_Register_LegBirthFormatErrFmt": ["第{0}棒出生日期格式应为 yyyy-MM-dd", "Leg {0}'s date of birth must be in yyyy-MM-dd format"],
        "Str_Register_PleaseAtLeastOneRelayEvent": ["请至少添加一个接力项目", "Please add at least one relay event"],
        "Str_Register_PleaseSelectRelayEventFirst": ["请先选择接力项目", "Please select a relay event first"],
        "Str_Register_RelayJoinedQueueMsg": ["已加入接力报名列表，可继续录入下一支队", "Added to the relay registration list — you can enter the next team"],
        "Str_Register_RelayEditingQueueFmt": ["正在编辑接力队列第 {0} 条，修改后请再次点\"添加到接力报名列表\"", "Editing relay entry {0} — after making changes, click \"Add to Relay Registration List\" again"],
        "Str_Register_RelayQueueEmptyHint": ["列表为空，请先在上方录入接力队后\"添加到接力报名列表\"", "The list is empty — enter a relay team above, then \"Add to Relay Registration List\""],
        "Str_Register_RelaySubmitAllFmt": ["全部提交接力报名（{0} 队）", "Submit All Relay Registrations ({0} teams)"],
        "Str_Register_RelayQueueCountFmt": ["共 {0} 队", "{0} team(s) total"],
        "Str_Register_RelayQiMetaFmt": ["{0} 项 / {1} 棒", "{0} event(s) / {1} legs"],
        "Str_Register_RelayQueueEmptySubmit": ["接力列表为空，请先添加", "The relay list is empty — add an entry first"],
        "Str_Register_RelaySubmittingFmt": ["正在提交 {0} 支接力队……等待服务器结果", "Submitting {0} relay team(s)… waiting for the server"],
        "Str_Register_RelayResultOkTitle": ["接力报名提交成功", "Relay Registration Submitted"],
        "Str_Register_RelayUpdatedSummary": ["主服务器已更新该接力队（队名+性别+项目唯一），原有报名被新数据覆盖。", "The server updated this relay team (unique by team name + gender + event) — the previous registration was overwritten."],
        "Str_Register_RelayNewSummary": ["主服务器已通过本次接力报名，相关数据已写入比赛系统。", "The server accepted this relay registration, and the data has been written to the competition system."],
        "Str_Register_RelayBibFmt": ["（队伍号 {0}）", " (Team No. {0})"],
        "Str_Register_RelayLegCountFmt": ["：{0} 棒", ": {0} legs"],
        "Str_Register_RelayResultFailTitle": ["接力报名未通过", "Relay Registration Rejected"],
        "Str_Register_RelayResultFailDefault": ["主服务器反馈：接力队报名未通过。请修改后重新提交。", "Server feedback: the relay team registration was rejected. Fix it and resubmit."],
        "Str_Register_RelayMultiOkSummaryFmt": ["共 {0} 条（队×项目）全部通过。", "All {0} entries (team × event) were accepted."],
        "Str_Register_RelayUpdatedTag": [" [更新]", " [updated]"],
        "Str_Register_RelayNewTag": [" [新建]", " [new]"],
        "Str_Register_RelayPartialTitle": ["接力报名部分通过", "Relay Registration Partially Accepted"],
        "Str_Register_RelayMultiSummaryFmt": ["通过 {0} 条，未通过 {1} 条。未通过的请修改后重新添加到列表提交。", "{0} accepted, {1} rejected. Fix the rejected entries and re-add them to the list."],
        "Str_Register_RelayBibShortFmt": [" 队伍号 {0}", " Team No. {0}"],

        // ── query.html ────────────────────────────────────────
        "Str_Query_PageTitle": ["赛事信息查询", "Competition Information"],
        "Str_Query_Brand": ["赛事查询", "Query"],
        "Str_Query_LoginSub": ["赛事查询终端", "Query Terminal"],
        "Str_Common_Username": ["用户名", "Username"],
        "Str_Common_Password": ["密  码", "Password"],
        "Str_Common_RememberMe": ["记住登录名和密码", "Remember username & password"],
        "Str_Common_Login": ["登  录", "Log In"],
        "Str_Query_ChangePwdTitle": ["修改用户名 / 密码", "Change Username / Password"],
        "Str_Query_ChangePwdSub": ["浏览器本机账号（localStorage），确认后立即生效，下次登录用新账号。", "This account lives in this browser (localStorage) — changes apply immediately and take effect on the next login."],
        "Str_Query_OldPwd": ["原密码", "Current Password"],
        "Str_Query_NewUser": ["新用户名", "New Username"],
        "Str_Query_NewPwd": ["新密码", "New Password"],
        "Str_Query_ConfirmNewPwd": ["确认新密码", "Confirm New Password"],
        "Str_Query_ConfirmChangeBtn": ["确认修改", "Confirm"],
        "Str_Query_ChangePwdTip": ["修改用户名 / 密码", "Change Username / Password"],
        "Str_Query_ServerSettingsTip": ["服务器设置", "Server Settings"],
        "Str_Query_NavDataCenter": ["数据中心", "Data"],
        "Str_Query_NavHome": ["概览", "Overview"],
        "Str_Query_NavSchedule": ["赛程", "Schedule"],
        "Str_Query_NavHeats": ["分组", "Heats"],
        "Str_Query_NavAthletes": ["运动员", "Athletes"],
        "Str_Query_NavResultsSection": ["成绩与排名", "Results & Ranking"],
        "Str_Query_NavResults": ["成绩", "Results"],
        "Str_Query_NavRanking": ["总排名", "Rankings"],
        "Str_Query_NavMedals": ["奖牌榜", "Medal Table"],
        "Str_Query_NavTeams": ["团体总分", "Team Scores"],
        "Str_Query_NavDocsSection": ["资料", "Reference"],
        "Str_Query_NavRecords": ["纪录", "Records"],
        "Str_Query_NavReferees": ["裁判员", "Officials"],
        "Str_Query_HomeTitle": ["概览", "Overview"],
        "Str_Query_HomeSubtitle": ["实时赛事统计 + 当前进展", "Live statistics + current progress"],
        "Str_Query_CurrentHeat": ["当前组", "Current Heat"],
        "Str_Query_RecentFinished": ["🏁 最近完赛项目", "🏁 Recently Finished"],
        "Str_Query_ColSession": ["场次", "Session"],
        "Str_Query_ColEvent": ["项目", "Event"],
        "Str_Query_ColStatus": ["状态", "Status"],
        "Str_Query_ScheduleTitle": ["比赛日程", "Schedule"],
        "Str_Query_ScheduleSubtitle": ["所有项目按场次排列", "All events, ordered by session"],
        "Str_Query_SearchEventPlaceholder": ["🔍 搜索项目名 / 性别 / 年龄段", "🔍 Search event / gender / age group"],
        "Str_Query_AllSessions": ["全部场次", "All Sessions"],
        "Str_Query_AllStatus": ["全部状态", "All Status"],
        "Str_Query_StatusDone": ["已完赛", "Finished"],
        "Str_Query_StatusLive": ["进行中", "In Progress"],
        "Str_Query_StatusTodo": ["待赛", "Upcoming"],
        "Str_Query_ColDateTime": ["日期/时间", "Date/Time"],
        "Str_Query_ColEvNum": ["项次", "No."],
        "Str_Query_ColGender": ["性别", "Gender"],
        "Str_Query_ColAgeGroup": ["组别", "Age Group"],
        "Str_Query_ColStage": ["阶段", "Stage"],
        "Str_Query_ColHeatCount": ["组数", "Heats"],
        "Str_Query_HeatsTitle": ["比赛分组", "Heats"],
        "Str_Query_HeatsSubtitle": ["选择项目查看分组与道次", "Select an event to view heats and lanes"],
        "Str_Query_SelectEventEllipsis": ["选择项目 …", "Select an event…"],
        "Str_Query_AthletesTitle": ["运动员名册", "Athlete Roster"],
        "Str_Query_SearchAthletePlaceholder": ["🔍 搜索姓名 / 号码 / 单位", "🔍 Search name / bib / team"],
        "Str_Query_AllGenders": ["全部性别", "All Genders"],
        "Str_Query_AllAgeGroups": ["全部组别", "All Age Groups"],
        "Str_Query_ColBib": ["号码", "Bib"],
        "Str_Query_ColName": ["姓名", "Name"],
        "Str_Query_ColAge": ["年龄", "Age"],
        "Str_Query_ColTeam": ["单位", "Team"],
        "Str_Query_ColEvents": ["报名项目", "Registered Events"],
        "Str_Query_ColEntryTime": ["报名时间", "Entry Time"],
        "Str_Query_ResultsTitle": ["成绩查询", "Results"],
        "Str_Query_ResultsSubtitle": ["已完赛项目成绩", "Results for finished events"],
        "Str_Query_RankingTitle": ["项目总排名", "Event Rankings"],
        "Str_Query_RankingSubtitle": ["全部组合并排序（已完赛运动员）", "All heats merged and ranked (finished athletes)"],
        "Str_Query_MedalsTitle": ["奖牌榜", "Medal Table"],
        "Str_Query_MedalsSubtitle": ["按金/银/铜统计的单位排名", "Teams ranked by gold/silver/bronze"],
        "Str_Query_ColRank": ["名次", "Rank"],
        "Str_Query_ColGold": ["金 🥇", "Gold 🥇"],
        "Str_Query_ColSilver": ["银 🥈", "Silver 🥈"],
        "Str_Query_ColBronze": ["铜 🥉", "Bronze 🥉"],
        "Str_Query_ColMedalTotal": ["奖牌合计", "Total Medals"],
        "Str_Query_TeamsTitle": ["团体总分", "Team Scores"],
        "Str_Query_TeamsSubtitle": ["单位总积分（个人 + 接力 + 破纪录奖励）", "Total team points (individual + relay + record bonus)"],
        "Str_Query_Top10Teams": ["📊 前 10 名单位", "📊 Top 10 Teams"],
        "Str_Query_ColIndividualPts": ["个人分", "Individual Pts"],
        "Str_Query_ColRelayPts": ["接力分", "Relay Pts"],
        "Str_Query_ColRecordPts": ["破纪录", "Record Bonus"],
        "Str_Query_ColTotalPts": ["总分", "Total"],
        "Str_Query_RecordsTitle": ["赛事纪录", "Records"],
        "Str_Query_RecordsSubtitle": ["世界纪录 / 全国纪录 / 赛会纪录 等", "World / National / Meet records, etc."],
        "Str_Query_SearchRecordPlaceholder": ["🔍 搜索项目 / 持有人 / 单位", "🔍 Search event / holder / team"],
        "Str_Query_AllTypes": ["全部类型", "All Types"],
        "Str_Query_ColType": ["类型", "Type"],
        "Str_Query_ColResult": ["成绩", "Result"],
        "Str_Query_ColHolder": ["持有人", "Holder"],
        "Str_Query_ColDate": ["日期", "Date"],
        "Str_Query_ColLocation": ["地点", "Location"],
        "Str_Query_RefereesTitle": ["裁判员介绍", "Officials"],
        "Str_Query_RefereesSubtitle": ["本届赛事裁判员名单", "Officials for this competition"],
        "Str_Query_ColTitleLevel": ["头衔 / 级别", "Title / Level"],
        "Str_Query_ConnDialogTitle": ["🌐 连接到服务器", "🌐 Connect to Server"],
        "Str_Query_ConnDialogDesc": ["输入主服务器 IP 地址", "Enter the server's IP address"],
        "Str_Query_HostPlaceholder": ["如 192.168.1.100", "e.g. 192.168.1.100"],
        "Str_Query_WaitingData": ["等待数据 …", "Waiting for data…"],
        "Str_Query_SessionNumFmt": ["第 {0} 场", "Session {0}"],
        "Str_Query_NoMatchResults": ["没有匹配结果", "No matching results"],
        "Str_Query_SelectEventFirst": ["请选择项目", "Please select an event"],
        "Str_Query_NoFinishedYet": ["还没有完赛项目", "No events finished yet"],
        "Str_Query_NotStartedYet": ["尚未开始", "Not started yet"],
        "Str_Query_RaceStateWaiting": ["等待", "Waiting"],
        "Str_Query_RaceStateReady": ["就位", "Ready"],
        "Str_Query_RaceStateRacing": ["🔴 比赛中", "🔴 Racing"],
        "Str_Query_RaceStateFinished": ["已完赛", "Finished"],
        "Str_Query_SessionLabelFmt": ["第{0}场", "Session {0}"],
        "Str_Query_HeatOfCountFmt": ["第{0}组", "Heat {0}"],
        "Str_Query_HeatCountUnitFmt": ["{0} 组", "{0} heat(s)"],
        "Str_Query_CheckMark": ["✓ 已完赛", "✓ Finished"],
        "Str_Query_LiveMark": ["⚡ 进行中", "⚡ In Progress"],
        "Str_Query_HeatCardTitleFmt": ["🏊 第 {0} 组", "🏊 Heat {0}"],
        "Str_Query_CancelledBadge": ["已取消", "Cancelled"],
        "Str_Query_PersonCountFmt": ["{0} 人", "{0} athlete(s)"],
        "Str_Query_HeatCancelledInto": ["本组已并入其它组", "This heat has been merged into another"],
        "Str_Query_HeatEmpty": ["本组暂无运动员", "No athletes in this heat yet"],
        "Str_Query_ColLaneShort": ["道次", "Lane"],
        "Str_Query_ColSeedTime": ["报名成绩", "Seed Time"],
        "Str_Query_AthleteStatFmt": ["共 {0} 位运动员 (总报名次 {1})", "{0} athletes total (registration entries: {1})"],
        "Str_Query_ColRemark": ["备注", "Remark"],
        "Str_Query_HeatResultTitleFmt": ["第 {0} 组 成绩", "Heat {0} Results"],
        "Str_Query_ConfirmedBadge": ["✓ 已确认", "✓ Confirmed"],
        "Str_Query_NoConfirmedResults": ["本项目尚未有已确认成绩", "No confirmed results for this event yet"],
        "Str_Query_NoValidResults": ["还没有有效成绩", "No valid results yet"],
        "Str_Query_NoTeamData": ["尚无团体数据", "No team data yet"],
        "Str_Query_NoRecordsData": ["没有纪录数据", "No record data"],
        "Str_Query_NoRefereesData": ["尚无裁判员资料", "No officials data yet"],
        "Str_Query_RefereeDefaultTitle": ["裁判员", "Official"],
        "Str_Query_ClockPrefix": ["⏱ ", "⏱ "],
        "Str_Query_PleaseEnterUsername": ["请输入用户名", "Please enter a username"],
        "Str_Query_WrongCredentials": ["用户名或密码错误", "Incorrect username or password"],
        "Str_Query_WrongOldPwd": ["原密码错误", "Current password is incorrect"],
        "Str_Query_NewUserEmpty": ["新用户名不能为空", "New username cannot be empty"],
        "Str_Query_NewPwdEmpty": ["新密码不能为空", "New password cannot be empty"],
        "Str_Query_PwdMismatch": ["两次输入的新密码不一致", "The two new passwords do not match"],
        "Str_Query_PwdUpdated": ["用户名 / 密码 已更新.", "Username / password updated."],
        "Str_Query_ConnConnectingFmt": ["连接中…", "Connecting…"],
        "Str_Query_ConnAddrError": ["地址错误", "Invalid address"],
        "Str_Query_ConnConnectedFmt": ["已连接 {0}", "Connected to {0}"],
        "Str_Query_ConnUpdatedFmt": ["已连接 {0}（数据有更新）", "Connected to {0} (data updated)"],
        "Str_Query_ConnClosedRetrying": ["已断开 (重连中…)", "Disconnected (reconnecting…)"],
        "Str_Query_ConnFailedShort": ["连接失败", "Connection failed"],
        "Str_Query_GenderMaleShort": ["男子", "Male"],
        "Str_Query_GenderFemaleShort": ["女子", "Female"],
        "Str_Query_RaceProgress": ["比赛进度", "Progress"],
        "Str_Query_ProgressSubFmt": ["已完赛 {0} / {1} 组 · {2} / {3} 项", "Finished {0} / {1} heats · {2} / {3} events"],
        "Str_Query_Athletes": ["参赛运动员", "Athletes"],
        "Str_Query_FromTeamsFmt": ["来自 {0} 个单位", "From {0} teams"],
        "Str_Query_TotalEvents": ["总项目", "Total Events"],
        "Str_Query_FinishedEventsFmt": ["已完赛 {0} 项", "{0} finished"],
        "Str_Query_NewRecords": ["破纪录", "New Records"],
        "Str_Query_TimesUnit": ["人次", "entries"],
        "Str_Query_TotalHeats": ["总组数", "Total Heats"],
        "Str_Query_FinishedHeatsFmt": ["已完赛 {0} 组", "{0} finished"],
        "Str_Query_HeatOfTotalFmt": ["第 {0} / {1} 组", "Heat {0} / {1}"],
        "Str_Query_PoolMetaFmt": ["{0}m × {1}道", "{0}m × {1} lanes"],

        // ── display.html ──────────────────────────────────────
        "Str_Display_PageTitle": ["大屏幕", "Display"],
        "Str_Display_ColLane": ["道次", "Lane"],
        "Str_Display_ColRank": ["名次", "Rank"],
        "Str_Display_ColName": ["姓名", "Name"],
        "Str_Display_ColTeam": ["代表队", "Team"],
        "Str_Display_ColAgeGroup": ["组别", "Age Group"],
        "Str_Display_ColResult": ["成绩", "Result"],
        "Str_Display_ColRemark": ["备注", "Remark"],
        "Str_Display_Welcome": ["欢迎", "Welcome"],
        "Str_Display_AwardCeremony": ["颁奖典礼", "Award Ceremony"],
        "Str_Display_BgSettingsTip": ["大屏底色设置", "Display Background"],
        "Str_Display_FsSettingsTip": ["大屏字号 (Ctrl + / Ctrl -)", "Display Font Size (Ctrl + / Ctrl -)"],
        "Str_Display_FsSettingsTitle": ["🔤 大屏字号", "🔤 Font Size"],
        "Str_Display_GlobalScaleLabel": ["全局 (所有文字同时缩放)", "Global (scales all text together)"],
        "Str_Display_ResetGlobalScale": ["恢复 全局 1.0x", "Reset Global to 1.0x"],
        "Str_Display_CategoryScaleLabel": ["分类 (单独调整某一类文字)", "Categories (adjust one text type at a time)"],
        "Str_Display_ResetAllCategories": ["恢复 分类全部 1.0x", "Reset All Categories to 1.0x"],
        "Str_Display_FsShortcutHintFmt": ["快捷键 {0} / {1} / {2} 调全局<br>范围 0.5x ~ 3.0x", "Shortcuts {0} / {1} / {2} adjust globally<br>Range 0.5x ~ 3.0x"],
        "Str_Display_TextStyleTip": ["文字样式 (颜色/字体)", "Text Style (color/font)"],
        "Str_Display_TextStyleTitle": ["📝 文字样式 (颜色 / 字体)", "📝 Text Style (Color / Font)"],
        "Str_Display_ResetAllDefault": ["全部恢复默认", "Reset All to Default"],
        "Str_Display_ConfirmResetTextStyle": ["确定恢复全部 9 处文字 (颜色+字体) 为默认?", "Reset all 9 text styles (color+font) to default?"],
        "Str_Display_ConfirmResetFsParts": ["确定恢复 4 类分类字号为 1.0x?", "Reset the 4 category font sizes to 1.0x?"],
        "Str_Display_ResetToDefaultTip": ["恢复默认", "Reset to default"],
        "Str_Display_ResetTo1xTip": ["恢复 1.0x", "Reset to 1.0x"],
        "Str_Display_BgTitle": ["🎨 大屏底色", "🎨 Display Background"],
        "Str_Display_BgSolid": ["纯色", "Solid"],
        "Str_Display_BgGradient": ["渐变 (层次感)", "Gradient (depth)"],
        "Str_Display_BgMesh": ["高级混合 (深度感)", "Mesh (advanced depth)"],
        "Str_Display_BgGray": ["灰度", "Grayscale"],
        "Str_Display_BgPattern": ["图案", "Pattern"],
        "Str_Display_BgCustom": ["自定义", "Custom"],
        "Str_Display_BgColorLabel": ["颜色:", "Color:"],
        "Str_Display_BgImageLabel": ["图片:", "Image:"],
        "Str_Display_ResetBgDefault": ["恢复默认 (深邃蓝)", "Reset to Default (Deep Blue)"],
        "Str_Display_ConnectTitle": ["连接主服务器", "Connect to Server"],
        "Str_Display_ServerIpLabel": ["服务器 IP 地址", "Server IP Address"],
        "Str_Display_ConnectPrompt": ["请输入主服务器IP并点击连接", "Enter the server IP and click Connect"],
        "Str_Display_EnterIpFirst": ["请输入服务器IP", "Please enter the server IP"],
        "Str_Display_ConnectingFmt": ["连接中… {0}:3002", "Connecting… {0}:3002"],
        "Str_Display_ReenterIpPrompt": ["请重新输入服务器IP并点击连接", "Re-enter the server IP and click Connect"],
        "Str_Display_ConfirmCloseDisplay": ["确定要关闭大屏幕显示？", "Close the display screen?"],
        "Str_Display_SelectImageFile": ["请选择图片文件", "Please select an image file"],
        "Str_Display_LargeImageConfirmFmt": ["图片较大 ({0}KB), 可能因 localStorage 限制(~5MB)存不下. 继续?", "This image is large ({0}KB) and may not fit within the ~5MB localStorage limit. Continue?"],
        "Str_Display_ReadImageFailed": ["读取图片失败", "Failed to read the image"],
        "Str_Display_SaveFailedImageFmt": ["保存失败: 图片/数据太大无法存入 localStorage. 请用更小的图片.", "Save failed: the image/data is too large for localStorage. Please use a smaller image."],
        "Str_Display_NoScheduleYet": ["暂无赛程", "No schedule yet"],
        "Str_Display_HeatCountUnitFmt": ["{0}组", "{0} heats"],
        "Str_Display_TitleWithHostFmt": ["大屏幕 - {0}", "Display - {0}"],
        "Str_Display_TsKeyTitle": ["比赛名称", "Title"],
        "Str_Display_TsKeyEvent": ["比赛项目", "Event"],
        "Str_Display_TsKeyStage": ["赛次/组别", "Stage/Group"],
        "Str_Display_TsKeyTime": ["滚动时间", "Running Time"],
        "Str_Display_TsKeyHeader": ["表头", "Header"],
        "Str_Display_TsKeyLane": ["道次", "Lane"],
        "Str_Display_TsKeyRank": ["名次", "Rank"],
        "Str_Display_TsKeyName": ["姓名", "Name"],
        "Str_Display_TsKeyTeam": ["代表队", "Team"],
        "Str_Display_TsKeyResult": ["成绩", "Result"],
        "Str_Display_TsKeyRemark": ["备注", "Remark"],
        "Str_Display_TsKeyRecord": ["比赛纪录(第3行)", "Records (Row 3)"],
        "Str_Display_FsKeyTitle": ["比赛名称", "Title"],
        "Str_Display_FsKeyEvent": ["比赛项目 / 赛次组别", "Event / Stage-Group"],
        "Str_Display_FsKeyTime": ["比赛时间 (滚动时间)", "Time (running clock)"],
        "Str_Display_FsKeyHeader": ["表头 (道/名次/姓名/代表队/成绩/备注)", "Header (lane/rank/name/team/result/remark)"],
        "Str_Display_FsKeyInfo": ["运动员信息 (道次/姓名/成绩…)", "Athlete info (lane/name/result…)"],
        "Str_Display_FsKeyRecord": ["比赛纪录 (第3行)", "Records (Row 3)"],
        "Str_Display_CustomFont": ["自定义", "Custom"],
        "Str_Display_FontYaHei": ["微软雅黑", "Microsoft YaHei"],
        "Str_Display_FontHei": ["黑体", "SimHei"],
        "Str_Display_FontSong": ["宋体", "SimSun"],
        "Str_Display_FontKai": ["楷体", "KaiTi"],
        "Str_Display_FontFangSong": ["仿宋", "FangSong"],
        "Str_Display_FontLiShu": ["隶书", "LiSu"],
        "Str_Display_FontYouYuan": ["幼圆", "YouYuan"],
        "Str_Display_FontConsolas": ["Consolas (等宽)", "Consolas (monospace)"],
        "Str_Display_RankNumFmt": ["第 {0} 名", "Rank {0}"],

        // ── control.html ──────────────────────────────────────
        "Str_Ctrl_PageTitle": ["显示控制", "Display Control"],
        "Str_Ctrl_PreviewSizeLabel": ["预览大小:", "Preview size:"],
        "Str_Ctrl_SectionRaceView": ["比赛视图", "Race View"],
        "Str_Ctrl_SectionHonor": ["荣誉与介绍", "Honors & Intro"],
        "Str_Ctrl_SectionResources": ["资源 / 弹框", "Resources / Dialogs"],
        "Str_Ctrl_SectionStyle": ["大屏样式 / 切换", "Display Style / Toggle"],
        "Str_Ctrl_BtnStartList": ["出发表", "Start List"],
        "Str_Ctrl_BtnLiveRace": ["比赛视图", "Race View"],
        "Str_Ctrl_BtnHeatResult": ["组成绩", "Heat Result"],
        "Str_Ctrl_BtnRanking": ["总排名", "Rankings"],
        "Str_Ctrl_BtnTeamStandings": ["团体", "Team"],
        "Str_Ctrl_BtnAwards": ["颁奖", "Awards"],
        "Str_Ctrl_BtnReferees": ["裁判介绍", "Officials"],
        "Str_Ctrl_BtnWelcome": ["欢迎", "Welcome"],
        "Str_Ctrl_BtnPublish": ["成绩发布", "Publish Results"],
        "Str_Ctrl_BtnSchedule": ["比赛日程", "Schedule"],
        "Str_Ctrl_BtnMedia": ["图片 / 视频", "Image / Video"],
        "Str_Ctrl_BtnPpt": ["PPT 播放", "PPT Playback"],
        "Str_Ctrl_BtnDisplayStyle": ["大屏样式 (底色 / 字号 / 文字)", "Display Style (Background / Size / Text)"],
        "Str_Ctrl_RankingPickTitle": ["🏆 总排名 — 选择回放项目", "🏆 Rankings — Select Event to Replay"],
        "Str_Ctrl_AwardsPickTitle": ["🥇 颁奖 — 选择颁奖项目", "🥇 Awards — Select Award Event"],
        "Str_Ctrl_RecordsHiddenFmt": ["记录已隐藏 (点击显示 WR/CR)", "Records hidden (click to show WR/CR)"],
        "Str_Ctrl_RecordsShownFullFmt": ["记录显示 (点击隐藏 WR/CR)", "Records shown (click to hide WR/CR)"],
        "Str_Ctrl_RemarkShowReactionOnFmt": ["备注: 显反应时 (点击关)", "Remark: Reaction time shown (click to hide)"],
        "Str_Ctrl_RemarkShowReactionOffFmt": ["备注: 不显反应时 (点击开)", "Remark: Reaction time hidden (click to show)"],
        "Str_Ctrl_RecordsDefault": ["记录显示", "Records Shown"],
        "Str_Ctrl_RemarkDefault": ["显反应时", "Show Reaction"],
        "Str_Ctrl_MediaModalTitle": ["🖼️ 图片 / 视频", "🖼️ Image / Video"],
        "Str_Ctrl_HostPcFilesLabel": ["[主控 PC 文件]", "[Host PC files]"],
        "Str_Ctrl_ThisDeviceLabel": ["[本机文件]", "[This device]"],
        "Str_Ctrl_MediaDirDescFmt": [" 目录 (默认 contain + 循环 + 自动播放):", " folder (default: contain + loop + autoplay):"],
        "Str_Ctrl_MediaUploadDesc": [" 上传后立即播放 (建议 < 16 MB):", " Uploaded files play immediately (recommended < 16 MB):"],
        "Str_Ctrl_StopShow": ["停止显示", "Stop"],
        "Str_Ctrl_PptModalTitle": ["📊 PPT 播放", "📊 PPT Playback"],
        "Str_Ctrl_PptDirDescFmt": [" 目录 (翻页控制在主控):", " folder (page control stays on host):"],
        "Str_Ctrl_PptUploadDesc": [" 上传 PPT (建议 < 32 MB, 转换 + 翻页仍在主控):", " Upload a PPT (recommended < 32 MB; conversion + paging stay on host):"],
        "Str_Ctrl_ScheduleModalTitle": ["📅 显示比赛日程", "📅 Show Schedule"],
        "Str_Ctrl_ScheduleModalDesc": ["选择要在大屏显示日程的比赛场次:", "Select which session's schedule to show on the big screen:"],
        "Str_Ctrl_AllSessionsBtn": ["📅 全部场次", "📅 All Sessions"],
        "Str_Ctrl_RankingPickDefaultTitle": ["选择项目", "Select Event"],
        "Str_Ctrl_RankingPickDesc": ["只列出已完赛(决赛全部确认)的项目:", "Only finished events (all finals confirmed) are listed:"],
        "Str_Ctrl_PublishModalTitle": ["成绩发布到大屏", "Publish Results to Display"],
        "Str_Ctrl_PublishModalDesc": ["选择已完赛的比赛项目：", "Select a finished event:"],
        "Str_Ctrl_StyleModalTitle": ["🎨 大屏样式远程控制", "🎨 Remote Display Style Control"],
        "Str_Ctrl_StyleModalDesc": ["改动立刻推送到所有大屏 display.html, 服务器持久化保存.", "Changes push to all display.html screens immediately and are saved on the server."],
        "Str_Ctrl_BgColorLabel": ["底色", "Background"],
        "Str_Ctrl_BgHexPlaceholder": ["#0f172a 或 linear-gradient(...)", "#0f172a or linear-gradient(...)"],
        "Str_Ctrl_BgSwatchDeepBlue": ["深邃蓝", "Deep Blue"],
        "Str_Ctrl_BgSwatchPoolCyan": ["泳池青", "Pool Cyan"],
        "Str_Ctrl_BgSwatchOceanBlue": ["深海蓝", "Ocean Blue"],
        "Str_Ctrl_BgSwatchForestGreen": ["森林绿", "Forest Green"],
        "Str_Ctrl_BgSwatchViolet": ["紫罗兰", "Violet"],
        "Str_Ctrl_BgSwatchCharcoal": ["炭墨黑", "Charcoal Black"],
        "Str_Ctrl_BgSwatchOceanSky": ["深海到天空", "Ocean to Sky"],
        "Str_Ctrl_BgSwatchSunset": ["落日余晖", "Sunset Glow"],
        "Str_Ctrl_FontSizeLabel": ["字号 (0.8x ~ 3.0x)", "Font Size (0.8x ~ 3.0x)"],
        "Str_Ctrl_ResetBtn": ["复位", "Reset"],
        "Str_Ctrl_TextColorFontLabel": ["文字颜色 / 字体", "Text Color / Font"],
        "Str_Ctrl_TextKeyTitle": ["比赛名称", "Competition Name"],
        "Str_Ctrl_TextKeyEvent": ["比赛项目", "Event"],
        "Str_Ctrl_TextKeyTime": ["滚动时间", "Running Time"],
        "Str_Ctrl_TextKeyLane": ["道次", "Lane"],
        "Str_Ctrl_TextKeyRank": ["名次", "Rank"],
        "Str_Ctrl_TextKeyName": ["姓名", "Name"],
        "Str_Ctrl_TextKeyTeam": ["代表队", "Team"],
        "Str_Ctrl_TextKeyResult": ["成绩", "Result"],
        "Str_Ctrl_TextKeyRemark": ["备注", "Remark"],
        "Str_Ctrl_TextKeyRecord": ["比赛纪录(第3行)", "Record (3rd line)"],
        "Str_Ctrl_FontYaHei": ["微软雅黑", "Microsoft YaHei"],
        "Str_Ctrl_FontHei": ["黑体", "SimHei"],
        "Str_Ctrl_FontSong": ["宋体", "SimSun"],
        "Str_Ctrl_FontKai": ["楷体", "KaiTi"],
        "Str_Ctrl_FontFangSong": ["仿宋", "FangSong"],
        "Str_Ctrl_FontLiShu": ["隶书", "LiShu"],
        "Str_Ctrl_FontYouYuan": ["幼圆", "YouYuan"],
        "Str_Ctrl_FontArial": ["Arial", "Arial"],
        "Str_Ctrl_FontConsolas": ["Consolas (等宽)", "Consolas (monospace)"],
        "Str_Ctrl_FontImpact": ["Impact", "Impact"],
        "Str_Ctrl_FontCustom": ["自定义", "Custom"],
        "Str_Ctrl_BeforeUnloadConfirm": ["确定要关闭显示控制？", "Close the display control page?"],
        "Str_Ctrl_EnterServerIpPrompt": ["请输入服务器IP地址:", "Enter the server IP address:"],
        "Str_Ctrl_PleaseEnterServerIp": ["请输入服务器IP", "Please enter the server IP"],
        "Str_Ctrl_ConnConnecting": ["连接中…", "Connecting…"],
        "Str_Ctrl_ConnClosedRetrying": ["连接断开，重连中…", "Disconnected, reconnecting…"],
        "Str_Ctrl_ConnFailRetry": ["连接失败，是否重新设置服务器地址？", "Connection failed — reset the server address?"],
        "Str_Ctrl_ConnError": ["连接错误，请检查服务器IP", "Connection error — please check the server IP"],
        "Str_Ctrl_NotConnected": ["未连接服务器", "Not connected to server"],
        "Str_Ctrl_NotConnectedShort": ["未连接", "Not connected"],
        "Str_Ctrl_SentPrefixFmt": ["已发送: {0}", "Sent: {0}"],
        "Str_Ctrl_NoScheduleYetAlert": ["暂未收到服务器赛程数据，请稍后再试。\n（如果刚连接，请等待几秒后重试）",
            "Schedule data hasn't arrived from the server yet — please try again shortly.\n(If you just connected, wait a few seconds and retry.)"],
        "Str_Ctrl_NoFinishedEvents": ["暂无已完赛的比赛项目", "No finished events yet"],
        "Str_Ctrl_LoadingEllipsis": ["加载中...", "Loading..."],
        "Str_Ctrl_MediaDirEmpty": ["主控 PC <code>Media/</code> 目录暂无文件", "No files in the host PC's <code>Media/</code> folder yet"],
        "Str_Ctrl_PptDirEmpty": ["主控 PC <code>Documents/PPT/</code> 目录暂无 PPT", "No PPT files in the host PC's <code>Documents/PPT/</code> folder yet"],
        "Str_Ctrl_UnsupportedFileTypeFmt": ["不支持的文件类型: {0}", "Unsupported file type: {0}"],
        "Str_Ctrl_ReadingFileFmt": ["读取中: {0} ({1} MB)", "Reading: {0} ({1} MB)"],
        "Str_Ctrl_Uploading": ["上传中...", "Uploading..."],
        "Str_Ctrl_UploadPlayedFmt": ["已上传播放: {0}", "Uploaded and playing: {0}"],
        "Str_Ctrl_UploadDonePlaying": ["上传完成, 大屏播放中", "Upload complete — now playing on the display"],
        "Str_Ctrl_ReadFailed": ["读取失败", "Read failed"],
        "Str_Ctrl_UploadedPptFmt": ["已上传 PPT (主控转换 + 翻页): {0}", "PPT uploaded (host converts + pages): {0}"],
        "Str_Ctrl_UploadDoneConverting": ["上传完成, 主控转换中...", "Upload complete — host is converting..."],
        "Str_Ctrl_RequestedPptFmt": ["已请求播放 PPT (翻页控制在主控 PC): {0}", "Requested PPT playback (paging controlled on host PC): {0}"],
        "Str_Ctrl_NoSessionsYet": ["暂无场次", "No sessions yet"],
        "Str_Ctrl_ShowSessionFmt": ["已发送: 显示第{0}场", "Sent: show session {0}"],
        "Str_Ctrl_ShowAllSessions": ["已发送: 显示全部场次", "Sent: show all sessions"],
        "Str_Ctrl_NoRankingCandidates": ["暂无已完赛(决赛全部确认)的项目", "No finished events (all finals confirmed) yet"],
        "Str_Ctrl_ConfirmPublishFmt": ["确定发布 {0} {1} {2}{3} 的成绩到大屏？", "Publish the results of {0} {1} {2}{3} to the display?"],
        "Str_Ctrl_HeatSuffixFmt": [" 第{0}组", " Heat {0}"],
        "Str_Ctrl_RequestedPublishFmt": ["已请求发布: {0} {1} {2}", "Requested publish: {0} {1} {2}"],
        "Str_Ctrl_SentPlayFmt": ["已发送播放: {0}", "Sent play request: {0}"],

        // ── race_control.html ─────────────────────────────────
        "Str_RC_PageTitle": ["比赛控制台", "Race Control"],
        "Str_RC_LoginSubtitle": ["比赛控制", "Race Control"],
        "Str_RC_NoCompetitionSelected": ["未选择比赛", "No competition selected"],
        "Str_RC_MemoryLabel": ["内存:", "Memory:"],
        "Str_RC_LogReleaseMemRequested": ["已请求 PC 端释放内存", "Requested the PC to release memory"],
        "Str_RC_ReleaseMemTitle": ["远程请求主服务器/RTC 释放内存 (强制 GC + LOH 紧凑, 大堆下可能短暂卡顿)", "Remotely request the server/RTC to release memory (forces GC + LOH compaction; may briefly stutter under a large heap)"],
        "Str_RC_Release": ["释放", "Release"],
        "Str_RC_BatteryVoltageLabel": ["电池电压:", "Battery Voltage:"],
        "Str_RC_HwTimerLabel": ["硬件计时器:", "Hardware Timer:"],
        "Str_RC_HwConnectBtn": ["硬件连接", "Hardware Connection"],
        "Str_RC_MainServerLabel": ["主服务器:", "Server:"],
        "Str_RC_Offline": ["离线", "Offline"],
        "Str_RC_SettingsTitle": ["参数设置", "Settings"],
        "Str_RC_SettingsChooseCategory": ["选择要设置的分类:", "Choose a settings category:"],
        "Str_RC_ServerAddress": ["服务器地址", "Server Address"],
        "Str_RC_HubTimeParams": ["时间参数设置", "Time Parameters"],
        "Str_RC_HubPoolDevice": ["比赛泳池、设备状态设置", "Pool & Device Status Settings"],
        "Str_RC_HubManualBtn": ["手动按键管理", "Manual Button Management"],
        "Str_RC_HubAutoSavePath": ["成绩存盘路径", "Results Save Path"],
        "Str_RC_HubThermalPrint": ["热敏打印", "Thermal Printing"],
        "Str_RC_HwTimerConn": ["硬件计时器连接", "Hardware Timer Connection"],
        "Str_RC_HubChangePwd": ["用户名和密码", "Username & Password"],
        "Str_RC_TpCloseTime": ["泳道关闭时间", "Lane Close Time"],
        "Str_RC_TpSBDelay": ["出发台关闭延迟", "Start Block Close Delay"],
        "Str_RC_TpConfDelay": ["成绩确认关闭延迟", "Result Confirm Close Delay"],
        "Str_RC_TpFSThresh": ["抢跳判定阈值", "False Start Threshold"],
        "Str_RC_TpRelayFSThresh": ["接力交接棒抢跳判定阀值", "Relay Handoff False Start Threshold"],
        "Str_RC_TpSplitDisp": ["分段成绩显示时长", "Split Display Time"],
        "Str_RC_TpBlindReplaceDelay": ["盲表代替成绩延迟", "Blind Watch Replace Delay"],
        "Str_RC_TpReactionEventWindow": ["接力反应时事件窗口", "Relay Reaction Event Window"],
        "Str_RC_TpFirstPlaceHold": ["第1名成绩停留时间", "1st Place Hold Time"],
        "Str_RC_TpBigDisplayPageInterval": ["大屏翻屏时间", "Display Page Interval"],
        "Str_RC_UnitSec": ["秒", "sec"],
        "Str_RC_UnitSec09": ["秒(0-9)", "sec (0-9)"],
        "Str_RC_UnitSec110": ["秒(1-10)", "sec (1-10)"],
        "Str_RC_FinishPos": ["终点位置", "Finish Position"],
        "Str_RC_LeftEnd": ["左端", "Left End"],
        "Str_RC_RightEnd": ["右端", "Right End"],
        "Str_RC_ReactionTimeRT": ["反应时(RT)", "Reaction Time (RT)"],
        "Str_RC_On": ["打开", "On"],
        "Str_RC_Off": ["关闭", "Off"],
        "Str_RC_BlindReplTp": ["盲表代触板", "Blind Watch Replaces Touchpad"],
        "Str_RC_OnShort": ["开", "On"],
        "Str_RC_OffShort": ["关", "Off"],
        "Str_RC_ManualTpReplTp": ["手动TP代替真TP", "Manual TP Replaces Real TP"],
        "Str_RC_HwDevice": ["硬件设备", "Hardware Device"],
        "Str_RC_AlwaysOpen": ["一直打开", "Always Open"],
        "Str_RC_ByRaceFlow": ["按比赛流程", "By Race Flow"],
        "Str_RC_SBEdge": ["出发信号边沿", "Start Signal Edge"],
        "Str_RC_FallingEdge": ["下降沿", "Falling Edge"],
        "Str_RC_RisingEdge": ["上升沿", "Rising Edge"],
        "Str_RC_LaneOrder": ["道次顺序", "Lane Order"],
        "Str_RC_LaneOrderFwd": ["正序 0→9", "Forward 0→9"],
        "Str_RC_LaneOrderRev": ["逆序 9→0", "Reverse 9→0"],
        "Str_RC_PoolTouchpad": ["泳池触板", "Pool Touchpad"],
        "Str_RC_DualEnd": ["两端安装", "Both Ends"],
        "Str_RC_SingleEnd": ["单边安装", "Single End"],
        "Str_RC_DeviceStatusMgmt": ["设备状态管理", "Device Status Management"],
        "Str_RC_HubBlindCount": ["左右盲表数量设置", "Left/Right Blind Watch Count"],
        "Str_RC_HwConnByProxy": ["由服务器代理连接 (PC 端的 RTC/主服务器实际持有硬件链路)", "Connected via the server (the PC-side RTC/server actually holds the hardware link)"],
        "Str_RC_ConnMethod": ["连接方式", "Connection Method"],
        "Str_RC_NoConnect": ["不连接", "Not Connected"],
        "Str_RC_Serial": ["串口", "Serial"],
        "Str_RC_TcpClient": ["TCP 客户端", "TCP Client"],
        "Str_RC_RecvPort": ["接收端口", "Receive Port"],
        "Str_RC_TcpHost": ["TCP 主机", "TCP Host"],
        "Str_RC_TcpPort": ["TCP 端口", "TCP Port"],
        "Str_RC_ConnectHw": ["连接硬件", "Connect Hardware"],
        "Str_RC_Disconnect": ["断开", "Disconnect"],
        "Str_RC_DotNotConnected": ["● 未连接", "● Not connected"],
        "Str_RC_LogQuickConnectSerial": ["已请求 PC 端连接/断开串口", "Requested the PC to connect/disconnect the serial port"],
        "Str_RC_QuickConnectSerial": ["快连串口", "Quick Serial Connect"],
        "Str_RC_DeviceTest": ["设备测试", "Device Test"],
        "Str_RC_AutoSavePathDesc": ["浏览器本机存盘配置 (保存到本机 localStorage). 由于浏览器沙箱限制, 无法直接写入绝对路径; 点击\"打印成绩\"时会通过浏览器下载机制保存到本机默认下载目录, 文件名按此处的命名格式生成.",
            "This browser's local save configuration (saved to this browser's localStorage). Due to browser sandbox limits, an absolute path can't be written directly; clicking \"Print Result\" saves to this browser's default download folder, named per the format below."],
        "Str_RC_PathLabel": ["路径标签", "Path Label"],
        "Str_RC_FileNameFormat": ["文件名格式", "File Name Format"],
        "Str_RC_AutoDownload": ["自动下载", "Auto Download"],
        "Str_RC_OnAutoDownload": ["开 (确认成绩后自动下载)", "On (auto-download after confirming results)"],
        "Str_RC_SaveToLocal": ["保存到本机", "Save Locally"],
        "Str_RC_ThermalPrintDesc": ["浏览器本机打印配置. 点击\"打印成绩\"时按这里设置, 通过浏览器调起打印机 (Ctrl+P 同款). 主控 PC / RTC 的热敏打印是另一套配置, 互不影响.",
            "This browser's local print configuration. Clicking \"Print Result\" uses these settings via the browser's print dialog (same as Ctrl+P). The host PC / RTC's thermal printing is a separate configuration, unaffected by this."],
        "Str_RC_Enable": ["启用", "Enable"],
        "Str_RC_Enabled": ["启用", "Enabled"],
        "Str_RC_Disabled": ["禁用", "Disabled"],
        "Str_RC_Copies": ["份数", "Copies"],
        "Str_RC_Paper": ["纸张", "Paper"],
        "Str_RC_Paper80mm": ["80mm 热敏", "80mm Thermal"],
        "Str_RC_Paper58mm": ["58mm 热敏", "58mm Thermal"],
        "Str_RC_PaperA4": ["A4 普通纸", "A4 Plain Paper"],
        "Str_RC_AutoPrint": ["自动打印", "Auto Print"],
        "Str_RC_OnAutoPrint": ["开 (确认后自动打印)", "On (auto-print after confirming)"],
        "Str_RC_ChangePwdDesc": ["浏览器本机账号 (保存到 localStorage). 当前 race_control.html 连接服务器不验证账号, 此账号仅作本机操作员标识用 (写入比赛日志). 修改 PC 端 (主服务器 / RTC) 凭据请到对应机器的\"参数设置\"操作.",
            "This browser's local account (saved to localStorage). Connecting from race_control.html does not verify this account against the server — it's only used to identify the local operator (written into the race log). To change PC-side (server/RTC) credentials, use \"Settings\" on that machine."],
        "Str_RC_NewPwd": ["新密码", "New Password"],
        "Str_RC_FillIfNeeded": ["如需设置则填", "Fill in if you want to set one"],
        "Str_RC_ConfirmPwd": ["确认密码", "Confirm Password"],
        "Str_RC_TypeAgain": ["再输一次", "Type it again"],
        "Str_RC_OperatorNamePlaceholder": ["操作员名称", "Operator name"],
        "Str_RC_MediaUploadDesc": ["从<b>浏览器本机</b>选择文件, 上传到主服务器播放到大屏 (建议 &lt; 16 MB). 支持: png / jpg / bmp / gif / webp / mp4 / webm / ogg / m4v",
            "Choose a file from <b>this browser's device</b> and upload it to the server to play on the display (recommended &lt; 16 MB). Supports: png / jpg / bmp / gif / webp / mp4 / webm / ogg / m4v"],
        "Str_RC_LogStopMediaRequested": ["已请求停止媒体显示", "Requested to stop media playback"],
        "Str_RC_PptUploadDesc": ["从<b>浏览器本机</b>选择 PPT 文件, 上传到主服务器. 主控 PC 用 PowerPoint COM 转 PNG 后, 通过 SHOW_MEDIA 通道把每张幻灯片推送到大屏, 翻页控制窗口在主控 PC 弹出. 支持: .ppt / .pptx (建议 &lt; 32 MB)",
            "Choose a PPT file from <b>this browser's device</b> and upload it to the server. The host PC converts it to PNGs via the PowerPoint COM API and pushes each slide to the display over the SHOW_MEDIA channel; the page-turn control window opens on the host PC. Supports: .ppt / .pptx (recommended &lt; 32 MB)"],
        "Str_RC_BlindCountDesc": ["每道使用的盲表数量（1-3）。修改后将通过服务器同步到所有计时控制台与硬件计时控制器。", "The number of blind watches used per lane (1-3). Changes sync via the server to all timing consoles and the hardware timing controller."],
        "Str_RC_LeftBlindCount": ["左边 盲表数量", "Left Blind Watch Count"],
        "Str_RC_RightBlindCount": ["右边 盲表数量", "Right Blind Watch Count"],
        "Str_RC_DeviceStatus4State": ["泳道设备状态管理 (4 态)", "Lane Device Status Management (4 states)"],
        "Str_RC_DeviceStatusGrayHint": ["灰底列受 比赛泳池(单/双端) 与 盲表数量 配置控制, 此处不可编辑.", "Gray columns are controlled by the Pool (single/dual-end) and Blind Watch Count settings and cannot be edited here."],
        "Str_RC_SetAllInstalled": ["全部设为安装", "Set All to Installed"],
        "Str_RC_SetAllNotInstalled": ["全部设为未安装", "Set All to Not Installed"],
        "Str_RC_SetAllGood": ["全部设为好", "Set All to Good"],
        "Str_RC_SetAllBroken": ["全部设为坏", "Set All to Broken"],
        "Str_RC_ManualBtnUseSetting": ["手动按键 用/不用 设置", "Manual Button Use/Don't-Use Settings"],
        "Str_RC_SetAllUse": ["全部设为用", "Set All to Use"],
        "Str_RC_SetAllNotUse": ["全部设为不用", "Set All to Don't Use"],
        "Str_RC_ReadonlyModeExeTakenOver": ["只读模式 — EXE已接管控制", "Read-only mode — control taken over by the EXE"],
        "Str_RC_TimingSourceCompare": ["计时源对比", "Timing Source Compare"],
        "Str_RC_RaceLog": ["比赛日志", "Race Log"],
        "Str_RC_SplitLabel": ["分段:", "Split:"],
        "Str_RC_Finish": ["终点", "Finish"],
        "Str_RC_ClickLaneRowHint": ["点击泳道行查看计时源", "Click a lane row to view its timing sources"],
        "Str_RC_LaneEventLogHint": ["本组所选道次的实时事件 — 出发反应时 / 触板 / 盲表 (切道次可调出该道历史)", "Live events for the selected lane in this heat — start reaction / touchpad / blind watch (switch lanes to see that lane's history)"],
        "Str_RC_ClickOrTypeLaneHint": ["(请先点击或输入泳道号)", "(Click or enter a lane number first)"],
        "Str_RC_StateWaiting": ["等待", "Waiting"],
        "Str_RC_LogHeader": ["日志", "Log"],
        "Str_RC_RaceControl": ["比赛控制", "Race Control"],
        "Str_RC_TimerReset": ["计时复位", "Timer Reset"],
        "Str_RC_Ready": ["准备就绪", "Ready"],
        "Str_RC_ManualStart": ["M.发令", "M.Start"],
        "Str_RC_PauseClock": ["停表", "Pause Clock"],
        "Str_RC_ConfirmHeatResult": ["确认本组成绩", "Confirm Heat Result"],
        "Str_RC_PrintResult": ["打印成绩", "Print Result"],
        "Str_RC_PublishEventRanking": ["公布项目总排名 (存盘)", "Publish Event Ranking (Save)"],
        "Str_RC_LaneOps": ["泳道操作", "Lane Operations"],
        "Str_RC_LaneNum": ["道次", "Lane"],
        "Str_RC_CancelNote": ["取消备注", "Cancel Note"],
        "Str_RC_BlindWatchResult": ["盲表成绩", "Blind Watch Result"],
        "Str_RC_LaneOpen": ["道次打开", "Open Lane"],
        "Str_RC_LaneClose": ["道次关闭", "Close Lane"],
        "Str_RC_OpenAll": ["全部打开", "Open All"],
        "Str_RC_CloseAll": ["全部关闭", "Close All"],
        "Str_RC_ManualTimeInput": ["手动输入", "Manual Input"],
        "Str_RC_ManualSplitInput": ["手工补段", "Manual Split Input"],
        "Str_RC_DisplayControlSection": ["显示控制", "Display Control"],
        "Str_RC_TeamSpaced": ["团 体", "Team"],
        "Str_RC_AwardsSpaced": ["颁 奖", "Awards"],
        "Str_RC_WelcomeSpaced": ["欢 迎", "Welcome"],
        "Str_RC_MediaSlash": ["图片/视频", "Image/Video"],
        "Str_RC_LogOpenDisplayStyleRequested": ["已请求 PC 端弹大屏样式窗口", "Requested the PC to open the display style window"],
        "Str_RC_DisplayStyleShort": ["大屏样式", "Display Style"],
        "Str_RC_SystemHardware": ["系统硬件", "System Hardware"],
        "Str_RC_DeviceTestModeTitle": ["进入设备测试模式：所有触板/出发台/盲表打开，硬件来什么都接收显示，不计入比赛", "Enter device test mode: all touchpads/start blocks/blind watches open, all incoming hardware events are received and displayed, none count toward the race"],
        "Str_RC_AllFinishedFmt": [" 全部{0}人已完赛！\n\n", " — all {0} athletes finished!\n\n"],
        "Str_RC_AutoPromoteConfirmFmt": ["是否自动晋级前{0}名到{1}？\n（按成绩总排名）", "Auto-promote the top {0} to {1}?\n(ranked by result)"],
        "Str_RC_LogPromotedFmt": ["已确认晋级：{0}{1} {2} → {3}", "Promotion confirmed: {0}{1} {2} → {3}"],
        "Str_RC_LogAutoPromoteCancelled": ["已取消自动晋级，可在\"成绩与排名→晋级处理\"中手动操作", "Auto-promotion cancelled — you can promote manually under \"Results & Ranking → Promotion\""],
        "Str_RC_LogPromotionDoneFmt": ["晋级完成：{0} {1} → {2}（{3}人，{4}组）", "Promotion complete: {0} {1} → {2} ({3} athletes, {4} heats)"],
        "Str_RC_LogCmdRejectedFmt": ["命令被服务器拒绝({0}): {1}", "Command rejected by the server ({0}): {1}"],
        "Str_RC_CmdNotExecutedFmt": ["命令没有执行。\n\n原因：{0}", "The command was not executed.\n\nReason: {0}"],
        "Str_RC_ServerRejectedDefault": ["服务器拒绝", "Rejected by the server"],
        "Str_RC_HeatResultDefaultTitle": ["本组成绩", "Heat Result"],
        "Str_RC_PrintFailedFmt": ["打印失败: {0}", "Print failed: {0}"],
        "Str_RC_LogRemotePrintFailedFmt": ["远程打印失败: {0}", "Remote print failed: {0}"],
        "Str_RC_LogDisconnectedServer": ["已断开服务器", "Disconnected from server"],
        "Str_RC_LogServerAddrUpdatedFmt": ["服务器地址已更新: {0}", "Server address updated: {0}"],
        "Str_RC_LogConnectedServerFmt": ["已连接服务器 {0}", "Connected to server {0}"],
        "Str_RC_LogExeTakenOver": ["比赛控制已由 EXE 接管, 本页计时按钮停用", "Race control has been taken over by the EXE — this page's timing buttons are disabled"],
        "Str_RC_LogExeExited": ["EXE 已退出, 本页计时按钮恢复可用", "The EXE has exited — this page's timing buttons are available again"],
        "Str_RC_LogCmdNotSentExeFmt": ["命令未发送(比赛控制在 EXE 手里): {0}", "Command not sent (race control is held by the EXE): {0}"],
        "Str_RC_ExeTakenOverNoTimingCmd": ["比赛控制程序(EXE)正在接管，本页不能发计时命令。\n\n请在那台机器上操作；对方退出后本页自动恢复。", "The race control program (EXE) has taken over — this page cannot send timing commands.\n\nPlease operate on that machine; this page recovers automatically once it exits."],
        "Str_RC_LogCmdNotSentNotConnFmt": ["命令未发送(未连接服务器): {0}", "Command not sent (not connected to server): {0}"],
        "Str_RC_NotConnectedToServerHint": ["未连接到服务器（顶部\"服务器\"指示灯应为绿色）。\n请先确认服务器在运行，再点 全屏右上角 或 顶部\"服务器\"附近的连接按钮。", "Not connected to the server (the \"Server\" indicator at the top should be green).\nMake sure the server is running, then click the Connect button near \"Server\" at the top (or top-right in fullscreen)."],
        "Str_RC_LogWrCrBarFmt": ["请求大屏 WR/CR 横条 {0}", "Requested the display's WR/CR bar {0}"],
        "Str_RC_Hide": ["隐藏", "hidden"],
        "Str_RC_Show": ["显示", "shown"],
        "Str_RC_RecordsHiddenShort": ["记录已隐藏", "Records Hidden"],
        "Str_RC_LogRemarkReactionFmt": ["请求大屏 备注栏 反应时 {0}", "Requested the display's remark column reaction time {0}"],
        "Str_RC_RemarkHiddenShort": ["不显反应时", "Reaction Time Hidden"],
        "Str_RC_NoScheduleData": ["暂无赛程数据", "No schedule data yet"],
        "Str_RC_NoFinishedEvents2": ["暂无已完赛的比赛", "No finished events yet"],
        "Str_RC_PleaseEnterLaneNum": ["请输入泳道号", "Please enter a lane number"],
        "Str_RC_DescDNS": ["缺席未出发", "Absent / Did Not Start"],
        "Str_RC_DescDNF": ["中途退出", "Did Not Finish"],
        "Str_RC_DescDSQ": ["犯规取消资格", "Disqualified"],
        "Str_RC_ConfirmMarkLaneFmt": ["确认将泳道 {0} 标记为 {1}（{2}）？\n\n此操作将取消该泳道的成绩。", "Mark lane {0} as {1} ({2})?\n\nThis will cancel that lane's result."],
        "Str_RC_LogLaneMarkedFmt": ["泳道{0} 标记为 {1}", "Lane {0} marked as {1}"],
        "Str_RC_LogNoteCancelledFmt": ["泳道{0} 取消备注", "Lane {0} note cancelled"],
        "Str_RC_LogUsedBlindResultFmt": ["泳道{0} 使用盲表成绩", "Lane {0} using blind watch result"],
        "Str_RC_LogLaneOpenedFmt": ["泳道{0} 打开", "Lane {0} opened"],
        "Str_RC_LogLaneClosedFmt": ["泳道{0} 关闭", "Lane {0} closed"],
        "Str_RC_ManualTimeInputPromptFmt": ["泳道 {0} 手动输入成绩（如 49.23 或 1:23.45）：", "Manually enter the result for lane {0} (e.g. 49.23 or 1:23.45):"],
        "Str_RC_BadResultFormat": ["成绩格式不正确", "Invalid result format"],
        "Str_RC_ConfirmManualTimeFmt": ["确认将泳道 {0} 的成绩手动输入为 {1}？\n\n此操作将写入数据库。", "Manually set lane {0}'s result to {1}?\n\nThis will be written to the database."],
        "Str_RC_LogManualTimeInputFmt": ["泳道{0} 手动输入成绩: {1}", "Lane {0} manual result entered: {1}"],
        "Str_RC_PwdMismatch": ["两次密码不一致", "The two passwords do not match"],
        "Str_RC_LogOperatorAcctSaved": ["操作员账号已保存到本机 (浏览器 localStorage)", "Operator account saved locally (browser localStorage)"],
        "Str_RC_LogUploadedMediaFmt": ["已上传媒体到大屏: {0}", "Uploaded media to the display: {0}"],
        "Str_RC_LogUploadedPptFmt": ["已上传 PPT: {0} (主控 PC 转换并翻页)", "PPT uploaded: {0} (converted and paged on the host PC)"],
        "Str_RC_PleaseConnectServerFirst": ["请先连接服务器", "Please connect to the server first"],
        "Str_RC_ExeTakenOverHwConnect": ["比赛控制程序(EXE)正在接管，硬件请在那台机器上连接。", "The race control program (EXE) has taken over — connect hardware on that machine."],
        "Str_RC_DotConnecting": ["● 连接中...", "● Connecting..."],
        "Str_RC_ExeTakenOverHwOperate": ["比赛控制程序(EXE)正在接管，硬件请在那台机器上操作。", "The race control program (EXE) has taken over — operate hardware on that machine."],
        "Str_RC_DotDisconnected": ["● 已断开", "● Disconnected"],
        "Str_RC_ConfirmHeatResultFmt": ["确认本组成绩？\n\n{0}\n\n确认后成绩将锁定保存。", "Confirm this heat's result?\n\n{0}\n\nOnce confirmed, the result will be locked and saved."],
        "Str_RC_LogHeatResultConfirmed": ["已确认本组成绩", "Heat result confirmed"],
        "Str_RC_HeatResultNotConfirmedYet": ["当前组成绩未确认, 请先点 \"确认本组成绩\".", "This heat's result isn't confirmed yet — click \"Confirm Heat Result\" first."],
        "Str_RC_LogRemotePrintRequestFmt": ["请求远程打印: {0}", "Requested remote print: {0}"],
        "Str_RC_PopupBlocked": ["浏览器拦截了弹窗, 请允许此页面弹窗后再试.", "The browser blocked the popup — allow popups for this page and try again."],
        "Str_RC_LogPrintWindowOpenedFmt": ["远程打印窗口已打开: {0}", "Remote print window opened: {0}"],
        "Str_RC_OpenPrintWindowFailedFmt": ["打开打印窗口失败: {0}", "Failed to open the print window: {0}"],
        "Str_RC_LogRequestedShowScheduleAll": ["已请求大屏显示比赛日程 (全部场次)", "Requested the display to show the schedule (all sessions)"],
        "Str_RC_PleaseSelectEventFirst": ["请先在赛程导航中选择项目", "Please select an event in the schedule navigation first"],
        "Str_RC_ConfirmPublishRankingFmt": ["确定公布并存盘本项目总排名?\n\n{0}", "Publish and save this event's overall ranking?\n\n{0}"],
        "Str_RC_LogRequestedPublishRankingFmt": ["已请求公布项目总排名: {0}", "Requested to publish event ranking: {0}"],
        "Str_RC_PleaseSelectLaneFirst": ["请先选择泳道", "Please select a lane first"],
        "Str_RC_ManualSplitSegPromptFmt": ["泳道 {0} 补哪一段? (段号, 1=第1段)", "Which split for lane {0}? (segment number, 1 = 1st split)"],
        "Str_RC_SegNumMustBePositive": ["段号必须是 ≥1 的整数", "The segment number must be an integer ≥ 1"],
        "Str_RC_ManualSplitTimePrompt": ["该段累计时间? (格式 m:ss.xx 或 ss.xx, 如 1:25.43 或 85.43)", "Cumulative time for this split? (format m:ss.xx or ss.xx, e.g. 1:25.43 or 85.43)"],
        "Str_RC_LogManualSplitFmt": ["已请求手工补段 道{0} 第{1}段 累计{2}", "Requested manual split entry: lane {0}, split {1}, cumulative {2}"],
        "Str_RC_ConfirmTimerReset": ["确定计时复位？", "Confirm timer reset?"],
        "Str_RC_LogTimerResetKeepResult": ["计时复位（保留已确认成绩，自动切下一组）", "Timer reset (confirmed result kept; automatically switching to next heat)"],
        "Str_RC_LogTimerResetRestart": ["计时复位（重新发令）", "Timer reset (ready for a new start)"],
        "Str_RC_HeatConfirmedLockedNoRestart": ["当前组已确认成绩并锁定，不能重新开始比赛。\n请在赛程导航中切换到下一组。", "This heat's result is confirmed and locked — the race can't be restarted.\nSwitch to the next heat in the schedule navigation."],
        "Str_RC_LogHeatConfirmedNoRestart": ["当前组已确认成绩，不能再次开始", "This heat's result is confirmed — it can't be started again"],
        "Str_RC_ConfirmReadyFmt": ["确定让本组进入【准备就绪】状态？{0}\n", "Put this heat into [Ready] state?{0}\n"],
        "Str_RC_LogTimeParamsUpdated": ["时间参数已更新", "Time parameters updated"],
        "Str_RC_LogPoolDeviceUpdated": ["泳池/设备参数已更新", "Pool/device parameters updated"],
        "Str_RC_LogSavePathSaved": ["成绩存盘路径已保存到本机 localStorage", "Results save path saved locally (localStorage)"],
        "Str_RC_LogThermalSaved": ["热敏打印设置已保存到本机 localStorage", "Thermal print settings saved locally (localStorage)"],
        "Str_RC_LogBlindCountUpdatedFmt": ["盲表数量更新：左 {0}，右 {1}（已通过服务器同步到三端与硬件）", "Blind watch count updated: left {0}, right {1} (synced via the server to all three clients and the hardware)"],
        "Str_RC_LogManualBtnSettingsSent": ["手动按键设置已发送", "Manual button settings sent"],
        "Str_RC_DevNotInstalled": ["未安装", "Not Installed"],
        "Str_RC_DevInstall": ["安装", "Install"],
        "Str_RC_DevGood": ["好", "Good"],
        "Str_RC_DevBroken": ["坏", "Broken"],
        "Str_RC_DevInstalled2": ["已安装", "Installed"],
        "Str_RC_DevDamaged": ["损坏", "Damaged"],
        "Str_RC_DevNormal": ["正常", "Normal"],
        "Str_RC_LogAllDevicesSetFmt": ["全部设备设为{0}", "All devices set to {0}"],
        "Str_RC_LogDeviceStatusFmt": ["泳道{0} {1} → {2}", "Lane {0} {1} → {2}"],
        "Str_RC_LockedBySingleEndTitle": ["该端受单端配置锁定", "This end is locked by the single-end configuration"],
        "Str_RC_ActionSwitchEvent": ["切换项目", "switch event"],
        "Str_RC_ActionSwitchPrevHeat": ["切换到上一组", "switch to the previous heat"],
        "Str_RC_ActionSwitchNextHeat": ["切换到下一组", "switch to the next heat"],
        "Str_RC_RacingCannotReselectEvent": ["比赛进行中不能重新选择比赛项目。\n\n如需切换，请先点击\"计时复位\"结束当前比赛。", "Can't reselect the event while a race is in progress.\n\nTo switch, click \"Timer Reset\" to end the current race first."],
        "Str_RC_LogCannotDuringRaceFmt": ["比赛进行中不能{0}", "Can't {0} while a race is in progress"],
        "Str_RC_HeatUnconfirmedCannotFmt": ["当前组尚未确认成绩，不能{0}。\n请先点击\"确认成绩\"或\"计时复位\"。", "This heat's result isn't confirmed yet, so you can't {0}.\nClick \"Confirm Result\" or \"Timer Reset\" first."],
        "Str_RC_LogHeatUnconfirmedCannotFmt": ["当前组未确认成绩，不能{0}", "This heat's result isn't confirmed — can't {0}"],
        "Str_RC_LogSelectedPrefix": ["选择: ", "Selected: "],
        "Str_RC_LogManualBtnNotEnabledFmt": ["道{0} {1}手动按键未启用", "Lane {0} {1} manual button not enabled"],
        "Str_RC_LogManualTouchFmt": ["手动触板: 道{0} {1}", "Manual touch: lane {0} {1}"],
        "Str_RC_ConfirmEnterDeviceTest": ["确认进入设备测试模式？\n\n所有触板/出发台/盲表都将打开，硬件来什么数据都直接显示但不计入比赛成绩。\n再点同一按钮退出。", "Enter device test mode?\n\nAll touchpads/start blocks/blind watches will open; any incoming hardware data is shown directly but doesn't count toward the race.\nClick the same button again to exit."],
        "Str_RC_StateRacing": ["比赛中", "Racing"],
        "Str_RC_LoginErrEmptyFields": ["请输入用户名和密码。", "Please enter a username and password."],
        "Str_RC_LoginErrWrongCreds": ["用户名或密码错误，请重试。", "Incorrect username or password — please try again."],
        "Str_RC_ExeTakenOverBanner": ["⚠ 比赛控制程序(EXE)正在接管 —— 本页的计时按钮已停用。计时请在那台机器上操作；对方退出后本页自动恢复。",
            "⚠ The race control program (EXE) has taken over — this page's timing buttons are disabled. Please time on that machine; this page recovers automatically once it exits."],
        "Str_RC_PleaseEnterServerAddr": ["请输入服务器地址", "Please enter the server address"],
        "Str_RC_PleaseEnterServerIp": ["请输入主服务器 IP", "Please enter the server IP"]
    };

    var STORAGE_KEY = 'swimWebLang';

    function currentLang() {
        try { return localStorage.getItem(STORAGE_KEY) || 'zh'; } catch (e) { return 'zh'; }
    }
    function setLang(lang) {
        try { localStorage.setItem(STORAGE_KEY, lang); } catch (e) {}
    }
    function t(key) {
        var row = table[key];
        if (!row) return key;   // 缺key不崩, 退化显示key本身(安全网, 跟 Loc.T 一致)
        var idx = currentLang() === 'en' ? 1 : 0;
        return row[idx] != null ? row[idx] : row[0];
    }
    function f(key) {
        var s = t(key);
        var args = Array.prototype.slice.call(arguments, 1);
        for (var i = 0; i < args.length; i++) s = s.split('{' + i + '}').join(args[i]);
        return s;
    }
    // 性别/赛次 展示层转换 —— 只用于"给人看"的地方, 传入/传出服务器的原始值不要用这个
    function genderDisplay(zh) {
        if (zh === '男') return t('Str_Gender_Male');
        if (zh === '女') return t('Str_Gender_Female');
        if (zh === '混合') return t('Str_Gender_Mixed');
        return zh || '';
    }
    function stageDisplay(zh) {
        if (zh === '预赛') return t('Str_Stage_Prelim');
        if (zh === '半决赛') return t('Str_Stage_Semi');
        if (zh === '决赛') return t('Str_Stage_Final');
        return zh || '';
    }
    function apply() {
        document.querySelectorAll('[data-i18n]').forEach(function (el) {
            var key = el.getAttribute('data-i18n');
            var attr = el.getAttribute('data-i18n-attr');
            var val = t(key);
            if (attr) el.setAttribute(attr, val); else el.textContent = val;
            // data-i18n-title: 同一个元素除了主文案(textContent/属性)以外, 还要翻译 title 提示,
            // 值是另一个 key(不复用主 key, 因为 title 提示文案通常跟可见文字不一样)。
            var titleKey = el.getAttribute('data-i18n-title');
            if (titleKey) el.setAttribute('title', t(titleKey));
        });
        try { document.documentElement.lang = currentLang() === 'en' ? 'en' : 'zh-CN'; } catch (e) {}
        if (typeof window.onWebLocApplied === 'function') { try { window.onWebLocApplied(); } catch (e) {} }
    }
    function toggle() { setLang(currentLang() === 'en' ? 'zh' : 'en'); apply(); }

    return {
        table: table, t: t, f: f, apply: apply, toggle: toggle, currentLang: currentLang,
        genderDisplay: genderDisplay, stageDisplay: stageDisplay,
        // 2026-10-08 display.html 专用: 跟主服务器广播的 data.lang 同步(大屏是纯展示给观众看的,
        // 不该有自己的语言主张)。原来 setLang 只在闭包内部用, 这里额外导出, 不改 toggle() 本身
        // (query/register 等其它网页的"自己选语言"行为不受影响)。
        setLang: setLang
    };
})();
